-- ==========================================
-- PHẦN 1: TẠO CÁC BẢNG CHA (MỨC 1 - KHÔNG CHỨA KHÓA NGOẠI)
-- ==========================================

CREATE TABLE TAIKHOAN (
    TenDangNhap VARCHAR2(50) PRIMARY KEY,
    MatKhau VARCHAR2(255) NOT NULL,
    Quyen NVARCHAR2(50) NOT NULL,
    TrangThai NUMBER(1),
    Email VARCHAR2(100)
);

CREATE TABLE DANHMUC (
    MaDM VARCHAR2(20) PRIMARY KEY,
    TenDM NVARCHAR2(100) NOT NULL
);

CREATE TABLE KHOHANG (
    MaKho VARCHAR2(20) PRIMARY KEY,
    TenKho NVARCHAR2(100) NOT NULL,
    DiaChiKho NVARCHAR2(255)
);

CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR2(20) PRIMARY KEY,
    TenNCC NVARCHAR2(150) NOT NULL,
    DiaChi NVARCHAR2(255) NOT NULL,
    SDT VARCHAR2(15) NOT NULL,
    Email VARCHAR2(100)
);

CREATE TABLE KHUYENMAI (
    MaKM VARCHAR2(20) PRIMARY KEY,        
    TenKM NVARCHAR2(100) NOT NULL,
    PhanTramGiam NUMBER(5, 2) NOT NULL,   
    GiaTriToiThieu NUMBER(18, 2) DEFAULT 0, 
    GiamToiDa NUMBER(18, 2),              
    NgayBatDau DATE,
    NgayKetThuc DATE,
    SoLuotDung INTEGER DEFAULT 0,         
    TrangThai NVARCHAR2(50),               
    CONSTRAINT chk_phantram CHECK (PhanTramGiam > 0 AND PhanTramGiam <= 100)
);

-- ==========================================
-- PHẦN 2: TẠO CÁC BẢNG MỨC 2 (CON CỦA MỨC 1)
-- ==========================================

CREATE TABLE NHANVIEN (
    MaNV VARCHAR2(20) PRIMARY KEY,
    TenNV NVARCHAR2(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR2(10),
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    DiaChi NVARCHAR2(255),
    ChucVu NVARCHAR2(50),
    NgayVaoLam DATE,
    TrangThai NUMBER(1),
    TenDangNhap VARCHAR2(50),
    CONSTRAINT fk_nv_tk FOREIGN KEY (TenDangNhap) REFERENCES TAIKHOAN(TenDangNhap)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR2(20) PRIMARY KEY,
    TenKH NVARCHAR2(100) NOT NULL,
    SDT VARCHAR2(15) UNIQUE NOT NULL,
    DiemTichLuy INTEGER DEFAULT 0,
    Email VARCHAR2(100),
    TenDangNhap VARCHAR2(50),
    CONSTRAINT fk_kh_tk FOREIGN KEY (TenDangNhap) REFERENCES TAIKHOAN(TenDangNhap)
);

CREATE TABLE SANPHAM (
    MaSP VARCHAR2(20) PRIMARY KEY,
    MaDM VARCHAR2(20) NOT NULL,
    MaKho VARCHAR2(20) NOT NULL,
    TenSP NVARCHAR2(200) NOT NULL,
    MauSac NVARCHAR2(50),
    KichCo VARCHAR2(10),
    GiaBan NUMBER(18, 2) NOT NULL CHECK (GiaBan >= 0),
    SoLuongTon NUMBER DEFAULT 0 CHECK (SoLuongTon >= 0),
    TrangThai NVARCHAR2(50),
    HINHANH VARCHAR2(255), 
    CONSTRAINT fk_sp_dm FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM),
    CONSTRAINT fk_sp_kho FOREIGN KEY (MaKho) REFERENCES KHOHANG(MaKho)
);

-- ==========================================
-- PHẦN 3: TẠO CÁC BẢNG MỨC 3 (GIAO DỊCH & VẬN HÀNH)
-- ==========================================

CREATE TABLE DIACHI (
    MaDC VARCHAR2(20) PRIMARY KEY,
    MaKH VARCHAR2(20) NOT NULL,
    TenNguoiNhan NVARCHAR2(100),
    SDTNguoiNhan VARCHAR2(15) NOT NULL,
    TinhThanh NVARCHAR2(100),
    PhuongXa NVARCHAR2(100),
    DiaChiChiTiet NVARCHAR2(255),
    CONSTRAINT fk_dc_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH) ON DELETE CASCADE
);

CREATE TABLE GIOHANG (
    MaGH VARCHAR2(20) PRIMARY KEY,
    MaKH VARCHAR2(20) UNIQUE NOT NULL,
    NgayCapNhat DATE DEFAULT SYSDATE,
    CONSTRAINT fk_gh_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH) ON DELETE CASCADE
);

CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR2(20) PRIMARY KEY,
    MaNV VARCHAR2(20) NOT NULL,
    MaNCC VARCHAR2(20) NOT NULL,
    NgayNhap DATE DEFAULT SYSDATE,
    TongTien NUMBER(18, 2) DEFAULT 0,
    GhiChu NVARCHAR2(255),
    CONSTRAINT fk_pn_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT fk_pn_ncc FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE DONHANG (
    MaDH VARCHAR2(20) PRIMARY KEY,
    MaKH VARCHAR2(20),                
    MaNV VARCHAR2(20),       
    MaDC VARCHAR2(20),                
    MaKM VARCHAR2(20),
    LoaiDon NVARCHAR2(20) DEFAULT 'OFFLINE' CHECK (LoaiDon IN ('ONLINE', 'OFFLINE')),
    NgayDat DATE DEFAULT SYSDATE,
    NgayGiaoDuKien DATE,              
    TrangThai NVARCHAR2(50),          
    TongTien NUMBER(18, 2) DEFAULT 0,
    PhiShip NUMBER(18, 2) DEFAULT 0,  
    HinhThucThanhToan NVARCHAR2(50),  
    DiemThuong NUMBER DEFAULT 0,
    DiemSuDung NUMBER DEFAULT 0,
    GhiChu NVARCHAR2(255),
    CONSTRAINT fk_dh_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT fk_dh_nv FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT fk_dh_dc FOREIGN KEY (MaDC) REFERENCES DIACHI(MaDC),
    CONSTRAINT fk_dh_km FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM)
);

CREATE TABLE DANHGIA (
    MaDG VARCHAR2(20) PRIMARY KEY,
    MaKH VARCHAR2(20) NOT NULL,
    MaSP VARCHAR2(20) NOT NULL,
    SoSao NUMBER NOT NULL CHECK (SoSao BETWEEN 1 AND 5),
    NoiDung NVARCHAR2(500),
    NgayDanhGia DATE DEFAULT SYSDATE,
    CONSTRAINT fk_dg_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT fk_dg_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

-- ==========================================
-- PHẦN 4: TẠO CÁC BẢNG MỨC 4 (CHI TIẾT N-N)
-- ==========================================

CREATE TABLE CHITIET_GIOHANG (
    MaGH VARCHAR2(20) NOT NULL,
    MaSP VARCHAR2(20) NOT NULL,
    SoLuong NUMBER NOT NULL CHECK (SoLuong > 0),
    PRIMARY KEY (MaGH, MaSP),
    CONSTRAINT fk_ctgh_gh FOREIGN KEY (MaGH) REFERENCES GIOHANG(MaGH) ON DELETE CASCADE,
    CONSTRAINT fk_ctgh_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP) ON DELETE CASCADE
);

CREATE TABLE CHITIET_PHIEUNHAP (
    MaPN VARCHAR2(20) NOT NULL,
    MaSP VARCHAR2(20) NOT NULL,
    SoLuong NUMBER NOT NULL CHECK (SoLuong > 0),
    DonGiaNhap NUMBER(18, 2) DEFAULT 0 NOT NULL CHECK (DonGiaNhap >= 0),
    ThanhTien NUMBER DEFAULT 0 NOT NULL CHECK (ThanhTien >= 0),
    PRIMARY KEY (MaPN, MaSP),
    CONSTRAINT fk_ctpn_pn FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN) ON DELETE CASCADE,
    CONSTRAINT fk_ctpn_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE CHITIET_DONHANG (
    MaDH VARCHAR2(20) NOT NULL,
    MaSP VARCHAR2(20) NOT NULL,
    SoLuong NUMBER NOT NULL CHECK (SoLuong > 0),
    DonGia NUMBER(18, 2) NOT NULL,
    ThanhTien NUMBER,
    PRIMARY KEY (MaDH, MaSP),
    CONSTRAINT fk_ctdh_dh FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH) ON DELETE CASCADE,
    CONSTRAINT fk_ctdh_sp FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);
